-- Your SQL goes here
ALTER TABLE ONLY horus_images ALTER COLUMN date_added SET DEFAULT CURRENT_DATE;
ALTER TABLE ONLY horus_videos ALTER COLUMN date_added SET DEFAULT CURRENT_DATE;
ALTER TABLE ONLY horus_pastes ALTER COLUMN date_added SET DEFAULT CURRENT_DATE;
