stages:
  - mirror

GH mirror:
  stage: mirror
  image: debian:7-slim
  script:
    - mkdir -p ~/.ssh
    - echo -n "${GITMIRROR_DEPLOY_KEY}" > ~/.ssh/id_rsa
    - apt-get update
    - apt-get install -y git
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - git remote add github git@github.com:${GITHUB_REPOSITORY}
    - git push github --all 
    - echo "Mirrored to Github"
