stages:
  - mirror

GH mirror:
  stage: mirror
  image: alpine/git
  script:
    - echo -n "${GITMIRROR_DEPLOY_KEY}" > ~/.ssh/id_rsa
    - git remote add github git@github.com:${GITHUB_REPOSITORY}
    - git push --all github
    - git-mirror "${CI_PROJECT_DIR}" 
    - echo "Mirrored to Github"
