stages:
  - mirror

GH mirror:
  stage: mirror
  image: debian:7-slim
  script:
    - mkdir -p ~/.ssh
    - echo -n "${GITMIRROR_DEPLOY_KEY}" > ~/.ssh/id_rsa
    - apt-get update
    - apt-get install -y git
    - git remote add github git@github.com:${GITHUB_REPOSITORY}
    - GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa" git push --all github
    - echo "Mirrored to Github"
