[package]
name = "horus_server"
version = "0.1.0"
authors = ["Nicholas Donnelly <nick@donnelly.cc>"]

[dependencies]
rocket = "0.3.2"
rocket_codegen = "0.3.2"
diesel = { version = "0.16.0", features = ["chrono", "postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.9.0"
r2d2-diesel = "*"
r2d2 = "*"
serde = "1.0"
serde_json = "*"
serde_derive = "1.0"
regex = "0.2"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.3"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates", "json"]
