[development]
secret_key = "R7Yj2zCkoyKBPc1IWxQMiV910CEHytkCRRqJQ3sWfnQ=" 

[production]
secret_key = "jNDogDzODUsCxpYRDxazmZQIBHQdpO4Y5VZMCyVLRqU="
port = 443

[global.tls]
certs = "fullchain.pem"
key = "privkey.pem"
